# Generated by Django 4.0.4 on 2022-04-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('AN', 'Andaman Nikobar'), ('AP', 'Andhra Pradesh'), ('AR', 'Arunanchal Pradesh'), ('AS', 'Assam'), ('CA', 'Bihar'), ('CO', 'Chandigarh'), ('CT', 'Chattisgarh'), ('DE', 'Dadar and nagar haveli'), ('DC', 'Daman and dieu'), ('FL', 'Delhi'), ('GA', 'Goa'), ('HI', 'Gujrat'), ('ID', 'Haryana'), ('IL', 'Himanchal Pradesh'), ('IN', 'Jammu Kashmir'), ('IA', 'Jharkhand'), ('KS', 'Karnataka'), ('KY', 'Kerala'), ('LA', 'Lakshdweep'), ('ME', 'Madhya Pradesh'), ('MD', 'Maharashtra'), ('MA', 'Manipur'), ('MI', 'Meghalaya'), ('MN', 'Mizoram'), ('MS', 'Nagaland'), ('MO', 'Orrisa'), ('MT', 'Puduchhery'), ('NE', 'punjab'), ('NV', 'Nevada'), ('NH', 'Rajsthan'), ('NJ', 'Sikkim'), ('NM', 'Tamilnadu'), ('NY', 'Telangana'), ('NC', 'Tripura'), ('ND', 'Uttar Pradesh'), ('OH', 'Uttarkhand'), ('OK', 'West Bengal'), ('OR', 'New delhi'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=100),
        ),
    ]
